name: Test

on: [pull_request]

jobs:
  go-test:
    name: "Go Test"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: Install mise
        uses: jdx/mise-action@v3
      - uses: actions/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install tools
        run: mise install
      - name: Install mage
        run: mise exec -- go install github.com/magefile/mage@latest
      - name: Test
        run: mise exec -- mage test

  go-mod-tidy:
    name: "Go mod tidy"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
      - name: Install mise
        uses: jdx/mise-action@v3
      - uses: actions/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install tools
        run: mise install
      - name: Install mage
        run: mise exec -- go install github.com/magefile/mage@latest
      - name: Tidy check
        run: mise exec -- mage gomodtidy
